name: CI-Build-AMI

on:
  pull_request:
    branches:
      [ main ]
    types:
      [ closed ]

env:
  PKR_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
  PKR_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  PKR_VAR_dev_user: ${{ vars.DEV_USER }}
  PKR_VAR_demo_user: ${{ vars.DEMO_USER }}
  AWS_ACCESS_KEY_ID: ${{ secrets.DEMO_AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.DEMO_AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ vars.DEMO_AWS_REGION }}
  ASG_NAME: ${{ vars.DEMO_ASG_NAME }}


jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: sergeysova/jq-action@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Test with Maven
        run: mvn test

      - name: Build package
        run: mvn package -DskipTests

      - name: Setup `packer`
        uses: hashicorp/packer-github-actions@main
        with:
          version: 'latest'

      - name: Run `packer init`
        run: packer init ./packer/create_ami.pkr.hcl

      - name: Run `packer validate`
        run: packer validate ./packer/create_ami.pkr.hcl

      - name: Run `packer build`
        run: |
          packer build ./packer/create_ami.pkr.hcl 2>&1 | tee build.log
          tail -2 build.log | awk 'match($0, /ami-.*/) { print substr($0, RSTART, RLENGTH) }' > ami.txt
          aws ec2 describe-launch-templates --query 'LaunchTemplates[].LaunchTemplateId' > launchTemplates.json
          jq '.[0]' launchTemplates.json | tr -d '"' > launchTemplateId.txt
          aws ec2 create-launch-template-version --launch-template-id $(<launchTemplateId.txt) --source-version 1 --launch-template-data '{"ImageId":"'$(<ami.txt)'"}'
          aws autoscaling start-instance-refresh --auto-scaling-group-name $ASG_NAME

