name: CI

on:
  pull_request:
  push:
  workflow_dispatch:

env:
  PKR_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
  PKR_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  PKR_VAR_dev_user: ${{ vars.DEV_USER }}
  PKR_VAR_demo_user: ${{ vars.DEMO_USER }}

jobs:
  validate:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Test with Maven
        run: mvn test

      - name: Build package
        run: mvn package -DskipTests

      - name: Setup `packer`
        uses: hashicorp/packer-github-actions@main
        with:
          version: 'latest'

      - name: Run `packer init`
        run: packer init ./packer/create_ami.pkr.hcl

      - name: Run `packer validate`
        run: packer validate ./packer/create_ami.pkr.hcl
